name = "rekordbox-yir"
compatibility_date = "2025-12-06"
main = "src/worker/index.ts"
preview_urls = true

[vars]
# REKORDBOX_KEY will be set via .env or secrets

[assets]
directory = "./public"
binding = "ASSETS"

[[rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
fallthrough = false

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true
